[package]
name = "save4read"
version = "0.1.0"
authors = ["Kirill Gusakov <kgusakov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version = "3"}
url = "2.2.0"
askama = "0.10.3"

sqlx = { version = "0.4.0", features = [ "runtime-actix-rustls", "sqlite", "macros" ] }

[dev-dependencies]
futures = "0.3.8"
actix-rt = "1.1.1"